#!/bin/bash
if [ $# -ne 3 ]; then
   if [ $# -ne 4 ]; then
       echo "Usage: test_num side_num ai_num extra_args";
       exit;
   fi
fi
./SetAiController $2 lp_$3_ai.cfg ~/.local/share/wesnoth/1.11/saves/G$1.gz ~/.local/share/wesnoth/1.11/saves/A$1.gz
OPTIONS="--data-dir ../wesnoth-old/ --load A$1.gz --log-debug=ai/mod $4"
echo "OPTIONS: " 
echo $OPTIONS
./../wesnoth-old/wesnoth $OPTIONS
